config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  resources :call_charges
  resources :call_records
  resources :user_accounts
  resources :fnf_items
  resources :products
  resources :services
  resources :bonus_accounts
  resources :accumulators
  resources :short_codes
  resources :isd_tariffs
  resources :communities
  resources :offers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accumulator.rb
class Accumulator < ApplicationRecord
  belongs_to :user_account
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bonus_account.rb
class BonusAccount < ApplicationRecord
  belongs_to :user_account
end

app/models/call_charge.rb
class CallCharge < ApplicationRecord
  belongs_to :call_record
end

app/models/call_record.rb
class CallRecord < ApplicationRecord
  belongs_to :user_account
  has_one :call_charge
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :product
end

app/models/fnf_item.rb
class FnfItem < ApplicationRecord
  has_many :products
end

app/models/isd_tariff.rb
class IsdTariff < ApplicationRecord
end

app/models/offer.rb
class Offer < ApplicationRecord
  has_many :user_offers
  has_many :user_accounts, through: :user_offers
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :fnf_item
  belongs_to :community
  has_many :user_accounts
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :user_accounts
end

app/models/short_code.rb
class ShortCode < ApplicationRecord
end

app/models/user_account.rb
class UserAccount < ApplicationRecord
  belongs_to :product
  belongs_to :service
  has_many :bonus_accounts
  has_many :user_offers
  has_many :offers, through: :user_offers
  has_many :accumulators
  has_many :user_fnfs
  has_many :call_records
end

app/models/user_fnf.rb
class UserFnf < ApplicationRecord
  belongs_to :user_account
end

app/models/user_offer.rb
class UserOffer < ApplicationRecord
  belongs_to :user_account
  belongs_to :offer
end

app/models/user_product.rb
class UserProduct < ApplicationRecord
  belongs_to :user_account
  belongs_to :product
end

app/models/user_service.rb
class UserService < ApplicationRecord
  belongs_to :user_account
  belongs_to :service
end

app/controllers/user_accounts_controller.rb
class UserAccountsController < ApplicationController
  before_action :set_user_account, only: [:show, :edit, :update, :destroy]

  # GET /user_accounts
  # GET /user_accounts.json
  def index
    @user_accounts = UserAccount.all
  end

  # GET /user_accounts/1
  # GET /user_accounts/1.json
  def show
    @user_product = @user_account.product
    @user_service = @user_account.service
    @user_offers = @user_account.offers.all
    @user_bonus_account = @user_account.bonus_accounts.all
  end

  # GET /user_accounts/new
  def new
    @user_account = UserAccount.new
  end

  # GET /user_accounts/1/edit
  def edit
  end

  # POST /user_accounts
  # POST /user_accounts.json
  def create
    @user_account = UserAccount.new(user_account_params)

    respond_to do |format|
      if @user_account.save
        format.html { redirect_to @user_account, notice: 'User account was successfully created.' }
        format.json { render :show, status: :created, location: @user_account }
      else
        format.html { render :new }
        format.json { render json: @user_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_accounts/1
  # PATCH/PUT /user_accounts/1.json
  def update
    respond_to do |format|
      if @user_account.update(user_account_params)
        format.html { redirect_to @user_account, notice: 'User account was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_account }
      else
        format.html { render :edit }
        format.json { render json: @user_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_accounts/1
  # DELETE /user_accounts/1.json
  def destroy
    @user_account.destroy
    respond_to do |format|
      format.html { redirect_to user_accounts_url, notice: 'User account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_account
      @user_account = UserAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_account_params
      params.require(:user_account).permit(:phone, :name, :account_balance, :product_id, :service_id)
    end
end

app/helpers/fnf_items_helper.rb
module FnfItemsHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/user_accounts_helper.rb
module UserAccountsHelper
end

app/views/user_accounts/_form.html.erb
<%= form_for(user_account) do |f| %>
  <% if user_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_account.errors.count, "error") %> prohibited this user_account from being saved:</h2>

      <ul>
      <% user_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :account_balance %>
    <%= f.text_field :account_balance %>
  </div>

    <div class="field">
    <%= f.label :product_ids, "Products" %><br />
    <%= f.collection_select :product_id, Product.order(:name), :id, :name, {}, {multiple: false} %>

  </div>

  <div class="field">
    <%= f.label :service_ids, "Communities" %><br />
    <%= f.collection_select :service_id, Service.order(:name), :id, :name, {}, {multiple: false} %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_accounts/edit.html.erb
<h1>Editing User Account</h1>

<%= render 'form', user_account: @user_account %>

<%= link_to 'Show', @user_account %> |
<%= link_to 'Back', user_accounts_path %>

app/views/user_accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Phone</th>
      <th>Name</th>
      <th>Account balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_accounts.each do |user_account| %>
      <tr>
        <td><%= user_account.phone %></td>
        <td><%= user_account.name %></td>
        <td><%= user_account.account_balance %></td>
        <td><%= link_to 'Show', user_account %></td>
        <td><%= link_to 'Edit', edit_user_account_path(user_account) %></td>
        <td><%= link_to 'Destroy', user_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Account', new_user_account_path %>

app/views/user_accounts/new.html.erb
<h1>New User Account</h1>

<%= render 'form', user_account: @user_account %>

<%= link_to 'Back', user_accounts_path %>

app/views/user_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Phone:</strong>
  <%= @user_account.phone %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user_account.name %>
</p>

<p>
  <strong>Account balance:</strong>
  <%= @user_account.account_balance %>
</p>

<%= link_to 'Edit', edit_user_account_path(@user_account) %> |
<%= link_to 'Back', user_accounts_path %>