config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  resources :call_charges
  resources :call_records
  resources :user_accounts
  resources :fnf_items
  resources :products
  resources :services
  resources :bonus_accounts
  resources :accumulators
  resources :short_codes
  resources :isd_tariffs
  resources :communities
  resources :offers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accumulator.rb
class Accumulator < ApplicationRecord
  belongs_to :user_account
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bonus_account.rb
class BonusAccount < ApplicationRecord
  belongs_to :user_account
end

app/models/call_charge.rb
class CallCharge < ApplicationRecord
  belongs_to :call_record
end

app/models/call_record.rb
class CallRecord < ApplicationRecord
  belongs_to :user_account
  has_one :call_charge
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :product
end

app/models/fnf_item.rb
class FnfItem < ApplicationRecord
  has_many :products
end

app/models/isd_tariff.rb
class IsdTariff < ApplicationRecord
end

app/models/offer.rb
class Offer < ApplicationRecord
  has_many :user_offers
  has_many :user_accounts, through: :user_offers
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :fnf_item
  belongs_to :community
  has_many :user_accounts
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :user_accounts
end

app/models/short_code.rb
class ShortCode < ApplicationRecord
end

app/models/user_account.rb
class UserAccount < ApplicationRecord
  belongs_to :product
  belongs_to :service
  has_many :bonus_accounts
  has_many :user_offers
  has_many :offers, through: :user_offers
  has_many :accumulators
  has_many :user_fnfs
  has_many :call_records
end

app/models/user_fnf.rb
class UserFnf < ApplicationRecord
  belongs_to :user_account
end

app/models/user_offer.rb
class UserOffer < ApplicationRecord
  belongs_to :user_account
  belongs_to :offer
end

app/models/user_product.rb
class UserProduct < ApplicationRecord
  belongs_to :user_account
  belongs_to :product
end

app/models/user_service.rb
class UserService < ApplicationRecord
  belongs_to :user_account
  belongs_to :service
end

app/controllers/fnf_items_controller.rb
class FnfItemsController < ApplicationController
  before_action :set_fnf_item, only: [:show, :edit, :update, :destroy]

  # GET /fnf_items
  # GET /fnf_items.json
  def index
    @fnf_items = FnfItem.all
  end

  # GET /fnf_items/1
  # GET /fnf_items/1.json
  def show
  end

  # GET /fnf_items/new
  def new
    @fnf_item = FnfItem.new
  end

  # GET /fnf_items/1/edit
  def edit
  end

  # POST /fnf_items
  # POST /fnf_items.json
  def create
    @fnf_item = FnfItem.new(fnf_item_params)

    respond_to do |format|
      if @fnf_item.save
        format.html { redirect_to @fnf_item, notice: 'Fnf item was successfully created.' }
        format.json { render :show, status: :created, location: @fnf_item }
      else
        format.html { render :new }
        format.json { render json: @fnf_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fnf_items/1
  # PATCH/PUT /fnf_items/1.json
  def update
    respond_to do |format|
      if @fnf_item.update(fnf_item_params)
        format.html { redirect_to @fnf_item, notice: 'Fnf item was successfully updated.' }
        format.json { render :show, status: :ok, location: @fnf_item }
      else
        format.html { render :edit }
        format.json { render json: @fnf_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fnf_items/1
  # DELETE /fnf_items/1.json
  def destroy
    @fnf_item.destroy
    respond_to do |format|
      format.html { redirect_to fnf_items_url, notice: 'Fnf item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fnf_item
      @fnf_item = FnfItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fnf_item_params
      params.require(:fnf_item).permit(:no_of_fnf, :pulse, :fnf_on_net_tariff, :fnf_off_net_tariff, :fnf_atw, :fnf_priority)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fnf_items_helper.rb
module FnfItemsHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/fnf_items/_form.html.erb
<%= form_for(fnf_item) do |f| %>
  <% if fnf_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fnf_item.errors.count, "error") %> prohibited this fnf_item from being saved:</h2>

      <ul>
      <% fnf_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :no_of_fnf %>
    <%= f.number_field :no_of_fnf %>
  </div>

  <div class="field">
    <%= f.label :pulse %>
    <%= f.text_field :pulse %>
  </div>

  <div class="field">
    <%= f.label :fnf_on_net_tariff %>
    <%= f.text_field :fnf_on_net_tariff %>
  </div>

  <div class="field">
    <%= f.label :fnf_off_net_tariff %>
    <%= f.text_field :fnf_off_net_tariff %>
  </div>

  <div class="field">
    <%= f.label :fnf_atw %>
    <%= f.text_field :fnf_atw %>
  </div>

  <div class="field">
    <%= f.label :fnf_priority %>
    <%= f.number_field :fnf_priority %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fnf_items/edit.html.erb
<h1>Editing Fnf Item</h1>

<%= render 'form', fnf_item: @fnf_item %>

<%= link_to 'Show', @fnf_item %> |
<%= link_to 'Back', fnf_items_path %>

app/views/fnf_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fnf Items</h1>

<table>
  <thead>
    <tr>
      <th>No of fnf</th>
      <th>Pulse</th>
      <th>Fnf on net tariff</th>
      <th>Fnf off net tariff</th>
      <th>Fnf atw</th>
      <th>Fnf priority</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fnf_items.each do |fnf_item| %>
      <tr>
        <td><%= fnf_item.no_of_fnf %></td>
        <td><%= fnf_item.pulse %></td>
        <td><%= fnf_item.fnf_on_net_tariff %></td>
        <td><%= fnf_item.fnf_off_net_tariff %></td>
        <td><%= fnf_item.fnf_atw %></td>
        <td><%= fnf_item.fnf_priority %></td>
        <td><%= link_to 'Show', fnf_item %></td>
        <td><%= link_to 'Edit', edit_fnf_item_path(fnf_item) %></td>
        <td><%= link_to 'Destroy', fnf_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fnf Item', new_fnf_item_path %>

app/views/fnf_items/new.html.erb
<h1>New Fnf Item</h1>

<%= render 'form', fnf_item: @fnf_item %>

<%= link_to 'Back', fnf_items_path %>

app/views/fnf_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>No of fnf:</strong>
  <%= @fnf_item.no_of_fnf %>
</p>

<p>
  <strong>Pulse:</strong>
  <%= @fnf_item.pulse %>
</p>

<p>
  <strong>Fnf on net tariff:</strong>
  <%= @fnf_item.fnf_on_net_tariff %>
</p>

<p>
  <strong>Fnf off net tariff:</strong>
  <%= @fnf_item.fnf_off_net_tariff %>
</p>

<p>
  <strong>Fnf atw:</strong>
  <%= @fnf_item.fnf_atw %>
</p>

<p>
  <strong>Fnf priority:</strong>
  <%= @fnf_item.fnf_priority %>
</p>

<%= link_to 'Edit', edit_fnf_item_path(@fnf_item) %> |
<%= link_to 'Back', fnf_items_path %>