config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  resources :call_charges
  resources :call_records
  resources :user_accounts
  resources :fnf_items
  resources :products
  resources :services
  resources :bonus_accounts
  resources :accumulators
  resources :short_codes
  resources :isd_tariffs
  resources :communities
  resources :offers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accumulator.rb
class Accumulator < ApplicationRecord
  belongs_to :user_account
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bonus_account.rb
class BonusAccount < ApplicationRecord
  belongs_to :user_account
end

app/models/call_charge.rb
class CallCharge < ApplicationRecord
  belongs_to :call_record
end

app/models/call_record.rb
class CallRecord < ApplicationRecord
  belongs_to :user_account
  has_one :call_charge
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :product
end

app/models/fnf_item.rb
class FnfItem < ApplicationRecord
  has_many :products
end

app/models/isd_tariff.rb
class IsdTariff < ApplicationRecord
end

app/models/offer.rb
class Offer < ApplicationRecord
  has_many :user_offers
  has_many :user_accounts, through: :user_offers
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :fnf_item
  belongs_to :community
  has_many :user_accounts
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :user_accounts
end

app/models/short_code.rb
class ShortCode < ApplicationRecord
end

app/models/user_account.rb
class UserAccount < ApplicationRecord
  belongs_to :product
  belongs_to :service
  has_many :bonus_accounts
  has_many :user_offers
  has_many :offers, through: :user_offers
  has_many :accumulators
  has_many :user_fnfs
  has_many :call_records
end

app/models/user_fnf.rb
class UserFnf < ApplicationRecord
  belongs_to :user_account
end

app/models/user_offer.rb
class UserOffer < ApplicationRecord
  belongs_to :user_account
  belongs_to :offer
end

app/models/user_product.rb
class UserProduct < ApplicationRecord
  belongs_to :user_account
  belongs_to :product
end

app/models/user_service.rb
class UserService < ApplicationRecord
  belongs_to :user_account
  belongs_to :service
end

app/controllers/accumulators_controller.rb
class AccumulatorsController < ApplicationController
  before_action :set_accumulator, only: [:show, :edit, :update, :destroy]

  # GET /accumulators
  # GET /accumulators.json
  def index
    @accumulators = Accumulator.all
  end

  # GET /accumulators/1
  # GET /accumulators/1.json
  def show
  end

  # GET /accumulators/new
  def new
    @accumulator = Accumulator.new
  end

  # GET /accumulators/1/edit
  def edit
  end

  # POST /accumulators
  # POST /accumulators.json
  def create
    @accumulator = Accumulator.new(accumulator_params)

    respond_to do |format|
      if @accumulator.save
        format.html { redirect_to @accumulator, notice: 'Accumulator was successfully created.' }
        format.json { render :show, status: :created, location: @accumulator }
      else
        format.html { render :new }
        format.json { render json: @accumulator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accumulators/1
  # PATCH/PUT /accumulators/1.json
  def update
    respond_to do |format|
      if @accumulator.update(accumulator_params)
        format.html { redirect_to @accumulator, notice: 'Accumulator was successfully updated.' }
        format.json { render :show, status: :ok, location: @accumulator }
      else
        format.html { render :edit }
        format.json { render json: @accumulator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accumulators/1
  # DELETE /accumulators/1.json
  def destroy
    @accumulator.destroy
    respond_to do |format|
      format.html { redirect_to accumulators_url, notice: 'Accumulator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accumulator
      @accumulator = Accumulator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def accumulator_params
      params.require(:accumulator).permit(:acc_val_change, :acc_val_available)
    end
end

app/helpers/accumulators_helper.rb
module AccumulatorsHelper
end

app/helpers/fnf_items_helper.rb
module FnfItemsHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/accumulators/_form.html.erb
<%= form_for(accumulator) do |f| %>
  <% if accumulator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(accumulator.errors.count, "error") %> prohibited this accumulator from being saved:</h2>

      <ul>
      <% accumulator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :acc_val_change %>
    <%= f.text_field :acc_val_change %>
  </div>

  <div class="field">
    <%= f.label :acc_val_available %>
    <%= f.text_field :acc_val_available %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accumulators/edit.html.erb
<h1>Editing Accumulator</h1>

<%= render 'form', accumulator: @accumulator %>

<%= link_to 'Show', @accumulator %> |
<%= link_to 'Back', accumulators_path %>

app/views/accumulators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accumulators</h1>

<table>
  <thead>
    <tr>
      <th>Acc val change</th>
      <th>Acc val available</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accumulators.each do |accumulator| %>
      <tr>
        <td><%= accumulator.acc_val_change %></td>
        <td><%= accumulator.acc_val_available %></td>
        <td><%= link_to 'Show', accumulator %></td>
        <td><%= link_to 'Edit', edit_accumulator_path(accumulator) %></td>
        <td><%= link_to 'Destroy', accumulator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Accumulator', new_accumulator_path %>

app/views/accumulators/new.html.erb
<h1>New Accumulator</h1>

<%= render 'form', accumulator: @accumulator %>

<%= link_to 'Back', accumulators_path %>

app/views/accumulators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Acc val change:</strong>
  <%= @accumulator.acc_val_change %>
</p>

<p>
  <strong>Acc val available:</strong>
  <%= @accumulator.acc_val_available %>
</p>

<%= link_to 'Edit', edit_accumulator_path(@accumulator) %> |
<%= link_to 'Back', accumulators_path %>