config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  resources :call_charges
  resources :call_records
  resources :user_accounts
  resources :fnf_items
  resources :products
  resources :services
  resources :bonus_accounts
  resources :accumulators
  resources :short_codes
  resources :isd_tariffs
  resources :communities
  resources :offers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/accumulator.rb
class Accumulator < ApplicationRecord
  belongs_to :user_account
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bonus_account.rb
class BonusAccount < ApplicationRecord
  belongs_to :user_account
end

app/models/call_charge.rb
class CallCharge < ApplicationRecord
  belongs_to :call_record
end

app/models/call_record.rb
class CallRecord < ApplicationRecord
  belongs_to :user_account
  has_one :call_charge
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :product
end

app/models/fnf_item.rb
class FnfItem < ApplicationRecord
  has_many :products
end

app/models/isd_tariff.rb
class IsdTariff < ApplicationRecord
end

app/models/offer.rb
class Offer < ApplicationRecord
  has_many :user_offers
  has_many :user_accounts, through: :user_offers
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :fnf_item
  belongs_to :community
  has_many :user_accounts
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :user_accounts
end

app/models/short_code.rb
class ShortCode < ApplicationRecord
end

app/models/user_account.rb
class UserAccount < ApplicationRecord
  belongs_to :product
  belongs_to :service
  has_many :bonus_accounts
  has_many :user_offers
  has_many :offers, through: :user_offers
  has_many :accumulators
  has_many :user_fnfs
  has_many :call_records
end

app/models/user_fnf.rb
class UserFnf < ApplicationRecord
  belongs_to :user_account
end

app/models/user_offer.rb
class UserOffer < ApplicationRecord
  belongs_to :user_account
  belongs_to :offer
end

app/models/user_product.rb
class UserProduct < ApplicationRecord
  belongs_to :user_account
  belongs_to :product
end

app/models/user_service.rb
class UserService < ApplicationRecord
  belongs_to :user_account
  belongs_to :service
end

app/controllers/isd_tariffs_controller.rb
class IsdTariffsController < ApplicationController
  before_action :set_isd_tariff, only: [:show, :edit, :update, :destroy]

  # GET /isd_tariffs
  # GET /isd_tariffs.json
  def index
    @isd_tariffs = IsdTariff.all
  end

  # GET /isd_tariffs/1
  # GET /isd_tariffs/1.json
  def show
  end

  # GET /isd_tariffs/new
  def new
    @isd_tariff = IsdTariff.new
  end

  # GET /isd_tariffs/1/edit
  def edit
  end

  # POST /isd_tariffs
  # POST /isd_tariffs.json
  def create
    @isd_tariff = IsdTariff.new(isd_tariff_params)

    respond_to do |format|
      if @isd_tariff.save
        format.html { redirect_to @isd_tariff, notice: 'Isd tariff was successfully created.' }
        format.json { render :show, status: :created, location: @isd_tariff }
      else
        format.html { render :new }
        format.json { render json: @isd_tariff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /isd_tariffs/1
  # PATCH/PUT /isd_tariffs/1.json
  def update
    respond_to do |format|
      if @isd_tariff.update(isd_tariff_params)
        format.html { redirect_to @isd_tariff, notice: 'Isd tariff was successfully updated.' }
        format.json { render :show, status: :ok, location: @isd_tariff }
      else
        format.html { render :edit }
        format.json { render json: @isd_tariff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /isd_tariffs/1
  # DELETE /isd_tariffs/1.json
  def destroy
    @isd_tariff.destroy
    respond_to do |format|
      format.html { redirect_to isd_tariffs_url, notice: 'Isd tariff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_isd_tariff
      @isd_tariff = IsdTariff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def isd_tariff_params
      params.require(:isd_tariff).permit(:pulse, :tariff, :number_prefix)
    end
end

app/helpers/fnf_items_helper.rb
module FnfItemsHelper
end

app/helpers/isd_tariffs_helper.rb
module IsdTariffsHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/isd_tariffs/_form.html.erb
<%= form_for(isd_tariff) do |f| %>
  <% if isd_tariff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(isd_tariff.errors.count, "error") %> prohibited this isd_tariff from being saved:</h2>

      <ul>
      <% isd_tariff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pulse %>
    <%= f.text_field :pulse %>
  </div>

  <div class="field">
    <%= f.label :tariff %>
    <%= f.text_field :tariff %>
  </div>

  <div class="field">
    <%= f.label :number_prefix %>
    <%= f.text_field :number_prefix %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/isd_tariffs/edit.html.erb
<h1>Editing Isd Tariff</h1>

<%= render 'form', isd_tariff: @isd_tariff %>

<%= link_to 'Show', @isd_tariff %> |
<%= link_to 'Back', isd_tariffs_path %>

app/views/isd_tariffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Isd Tariffs</h1>

<table>
  <thead>
    <tr>
      <th>Pulse</th>
      <th>Tariff</th>
      <th>Number prefix</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @isd_tariffs.each do |isd_tariff| %>
      <tr>
        <td><%= isd_tariff.pulse %></td>
        <td><%= isd_tariff.tariff %></td>
        <td><%= isd_tariff.number_prefix %></td>
        <td><%= link_to 'Show', isd_tariff %></td>
        <td><%= link_to 'Edit', edit_isd_tariff_path(isd_tariff) %></td>
        <td><%= link_to 'Destroy', isd_tariff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Isd Tariff', new_isd_tariff_path %>

app/views/isd_tariffs/new.html.erb
<h1>New Isd Tariff</h1>

<%= render 'form', isd_tariff: @isd_tariff %>

<%= link_to 'Back', isd_tariffs_path %>

app/views/isd_tariffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pulse:</strong>
  <%= @isd_tariff.pulse %>
</p>

<p>
  <strong>Tariff:</strong>
  <%= @isd_tariff.tariff %>
</p>

<p>
  <strong>Number prefix:</strong>
  <%= @isd_tariff.number_prefix %>
</p>

<%= link_to 'Edit', edit_isd_tariff_path(@isd_tariff) %> |
<%= link_to 'Back', isd_tariffs_path %>